# Lab-06 Logistic Regression

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import seaborn
%matplotlib inline

In [2]:
df = pd.read_csv('marital status.csv')

In [3]:
df

   age marital_status
0   25         Single
1   30        Married
2  NaN         Single
3   45       Divorced
4   35        Married
5   28         Single
6   40            NaN
7   55       Divorced
8    ,        Married
9   27         Single

## Checking Null/Nan Values

In [4]:
df.isnull().sum()

age               1
marital_status    1
dtype: int64

In [5]:
df = pd.read_csv('marital status_Log_Reg.csv')

In [6]:
df

    age  marital_status
0    25               0
1    30               1
2    60               0
3    45               1
4    35               1
5    28               0
6    40               1
7    55               1
8    37               1
9    27               0
10   26               0
11   32               1
12   35               0
13   47               1
14   37               1
15   29               0
16   41               1
17   53               1
18   45               1
19   25               0

In [7]:
df.isnull().sum()

age               0
marital_status    0
dtype: int64

## Filling null values of age column

In [8]:
updated_df = df
updated_df['age']=updated_df['age'].fillna(updated_df['age'].mean())
updated_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             20 non-null     int64
 1   marital_status  20 non-null     int64
dtypes: int64(2)
memory usage: 452.0 bytes

In [9]:
handle = df['marital_status'].median()

In [10]:
handle

np.float64(1.0)

## filling null values with median means handle

In [11]:
df.marital_status= df.marital_status.fillna(handle)